export default {
  main: [
    { label: "Open the app", url: "/app/", cta: true },
    { label: "Features", url: "/#features" },
    { label: "Docs", url: "/docs/" },
    { label: "Blog", url: "/blog/" },
    { label: "Glossary", url: "/glossary/" },
    { label: "Open source", url: "/open-source/" },
  ],
  app: [
    { label: "Dashboard", url: "/app/" },
    { label: "Budget", url: "/app/budget/" },
    { label: "Register", url: "/app/register/" },
    { label: "Calendar", url: "/app/calendar/" },
    { label: "Accounts", url: "/app/accounts/" },
    { label: "Categories", url: "/app/categories/" },
    { label: "Payees", url: "/app/payees/" },
    { label: "Recurring", url: "/app/scheduled/" },
    { label: "Reports", url: "/app/reports/" },
    { label: "Import", url: "/app/import/" },
    { label: "Export", url: "/app/export/" },
    { label: "Profiles", url: "/app/profiles/" },
    { label: "Settings", url: "/app/settings/" },
  ],
  footer: [
    { label: "Docs", url: "/docs/" },
    { label: "Blog", url: "/blog/" },
    { label: "Open source", url: "/open-source/" },
    { label: "Changelog", url: "/changelog/" },
    { label: "Accessibility", url: "/accessibility/" },
    { label: "Style guide", url: "/style-guide/" },
    { label: "Sitemap", url: "/sitemap/" },
    { label: "Privacy", url: "/privacy/" },
    { label: "Terms", url: "/terms/" },
  ],
};
