export default {
  title: "Project Budget",
  shortTitle: "Project Budget",
  tagline: "Envelope budgeting that lives in your browser.",
  description:
    "A free, open-source budgeting web app for envelope-style personal finance. Your data lives in your browser. No accounts, no servers, no bank connections.",
  url: process.env.SITE_URL || "https://projectbudget.org",
  author: "Project Budget",
  email: "hello@projectbudget.org",
  language: "en",
  locale: "en_US",
  themeColor: "#0f172a",
  ogImage: "/assets/img/og-default.jpg",
  repo: "https://github.com/jonajinga/project-budget",
  license: "MIT",
  storage: {
    prefix: "projectbudget:",
    themeKey: "projectbudget-theme",
    activeKey: "projectbudget:active",
    profilesKey: "projectbudget:profiles",
  },
  voice: {
    forbiddenWords: [
      "synergy",
      "leverage",
      "solutions",
      "robust",
      "passionate",
      "world-class",
      "best-in-class",
      "cutting-edge",
      "next-generation",
      "blazing",
      "lightning-fast",
    ],
  },
  umamiWebsiteId: "",
  cloudflareBeaconToken: "",
};
